import {supabaseServer} from './supabase/server';
import {localAuth,localUser,localLogout} from './local-auth';
import {asUser} from './local-db';
export const isLocal=()=>process.env.EDUKIDS_DATA_MODE!=='supabase';
export type Profile={id:string;alias:string;avatar:string;age_band:string;archived:boolean};
export async function identity(){if(isLocal())return localUser();const {data:{user}}=await (await supabaseServer()).auth.getUser();return user?{id:user.id,email:user.email??''}:null;}
export async function authenticate(action:string,email:string,password:string){if(isLocal())return {user:await localAuth(action,email,password),needsConfirmation:false};const db=await supabaseServer();const {data,error}=action==='signup'?await db.auth.signUp({email,password,options:{emailRedirectTo:process.env.APP_ORIGIN+'/auth/callback'}}):await db.auth.signInWithPassword({email,password});if(error)throw error;return {user:data.session&&data.user?{id:data.user.id,email:data.user.email??''}:null,needsConfirmation:!data.session};}
export async function logout(){if(isLocal())return localLogout();await (await supabaseServer()).auth.signOut();}
export async function profiles(uid:string):Promise<Profile[]>{if(isLocal())return asUser(uid,'select id,alias,avatar,age_band,archived from public.child_profiles where not archived order by created_at');const {data,error}=await (await supabaseServer()).from('child_profiles').select('id,alias,avatar,age_band,archived').eq('adult_id',uid).eq('archived',false).order('created_at');if(error)throw error;return data??[];}
export async function saveProfile(uid:string,b:{id?:string;alias:string;avatar:string;ageBand:string}){if(isLocal()){return asUser(uid,b.id?'update public.child_profiles set alias=$1,avatar=$2,age_band=$3 where id=$4 returning id':'insert into public.child_profiles(alias,avatar,age_band,adult_id) values($1,$2,$3,$4) returning id',[b.alias,b.avatar,b.ageBand,b.id??uid]);}const db=await supabaseServer();const values={adult_id:uid,alias:b.alias,avatar:b.avatar,age_band:b.ageBand};const {error}=b.id?await db.from('child_profiles').update(values).eq('id',b.id).eq('adult_id',uid):await db.from('child_profiles').insert(values);if(error)throw error;}
export async function settings(uid:string,pid:string){if(isLocal())return asUser(uid,'select activity_id,enabled,level from public.profile_activity where profile_id=$1',[pid]);const {data,error}=await (await supabaseServer()).from('profile_activity').select('activity_id,enabled,level').eq('profile_id',pid);if(error)throw error;return data;}
export async function saveSettings(uid:string,b:{profileId:string;game:string;enabled:boolean;level:number}){if(isLocal())return asUser(uid,'insert into public.profile_activity(profile_id,activity_id,enabled,level) values($1,$2,$3,$4) on conflict(profile_id,activity_id) do update set enabled=excluded.enabled,level=excluded.level',[b.profileId,b.game,b.enabled,b.level]);const {error}=await (await supabaseServer()).from('profile_activity').upsert({profile_id:b.profileId,activity_id:b.game,enabled:b.enabled,level:b.level});if(error)throw error;}
export async function sessions(uid:string,pid:string){if(isLocal())return asUser(uid,"select s.*,coalesce((select jsonb_agg(r order by r.created_at) from public.responses r where r.session_id=s.id),'[]'::jsonb) responses from public.play_sessions s where s.profile_id=$1 order by s.created_at desc limit 100",[pid]);const {data,error}=await (await supabaseServer()).from('play_sessions').select('id,activity_id,level,status,created_at,responses(item_id,answer,correct,hint_used,latency_ms,exposure_ms,attempt_no)').eq('profile_id',pid).order('created_at',{ascending:false}).limit(100);if(error)throw error;return data;}
export async function rpc(uid:string,name:'start_play'|'record_answer'|'finish_play',params:Record<string,unknown>){if(isLocal()){const keys=Object.keys(params);const rows=await asUser<{data:unknown}>(uid,`select public.${name}(${keys.map((k,i)=>`${k} => $${i+1}`).join(',')}) as data`,Object.values(params).map(v=>Array.isArray(v)?JSON.stringify(v):v));return rows[0]?.data;}const {data,error}=await (await supabaseServer()).rpc(name,params);if(error)throw error;return data;}
