'use client';
import Link from 'next/link';import {useEffect,useState} from 'react';import {request,toResults} from '@/lib/ui-data';import {games,summary,type Result} from '@/lib/games';
type Profile={id:string;alias:string;avatar:string;age_band:string};type Setting={activity_id:string;enabled:boolean;level:number};
export default function Family(){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[unlocked,setUnlocked]=useState(false),[profiles,setProfiles]=useState<Profile[]>([]),[profile,setProfile]=useState(''),[settings,setSettings]=useState<Setting[]>([]),[history,setHistory]=useState<Result[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState(''),[alias,setAlias]=useState(''),[avatar,setAvatar]=useState('star'),[band,setBand]=useState('7-8');
 async function load(pid=''){const d=await request('/api/data?area=family'+(pid?'&profile='+pid:''));setUnlocked(d.adultUnlocked);setEmail(d.email??'');setProfiles(d.profiles);setSettings(d.settings);setHistory(toResults(d.sessions));}
 useEffect(()=>{load().catch(()=>{});},[]);
 async function auth(action:string){setBusy(true);setError('');setMessage('');try{const r=await request('/api/auth',{action,email,password});setPassword('');if(r.needsConfirmation)setMessage('Revisa tu correo para confirmar la cuenta y después vuelve a entrar.');else await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(){setBusy(true);setError('');try{await request('/api/data',{action:'profile',id:editing||undefined,alias,avatar,ageBand:band});setAlias('');setEditing('');await load(profile);setMessage('Perfil guardado.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function configure(game:string,enabled:boolean,level:number){setBusy(true);setError('');try{await request('/api/data',{action:'settings',profileId:profile,game,enabled,level});await load(profile);setMessage('Configuración guardada. Se aplicará en la próxima actividad.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const totals=summary(history);
 return <main id="main" className="app-shell"><header className="app-header"><Link href="/" className="brand">edukids</Link><span className="tag">Familias</span><Link href="/jugar" className="button small">Zona infantil</Link></header><h1>Un lugar para acompañar</h1>{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="hint">{message}</p>}
 {!unlocked?<section className="panel auth-panel"><h2>Acceso adulto</h2><p>Entra con tu cuenta o créala para este entorno. Usa datos de prueba durante el desarrollo.</p><form onSubmit={e=>{e.preventDefault();void auth('login');}}><label>Correo electrónico<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Contraseña<input type="password" autoComplete="current-password" required minLength={8} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></label><div className="actions"><button className="primary" disabled={busy} type="submit">Entrar</button><button disabled={busy} type="button" onClick={()=>void auth('signup')}>Crear cuenta</button></div></form><p className="notice">El permiso para configurar dura cinco minutos. Después se vuelve a pedir la contraseña.</p></section>:<>
 <div className="actions"><button onClick={async()=>{await request('/api/auth',{action:'lock'});location.href='/jugar';}}>Ir a jugar y bloquear configuración</button><button onClick={async()=>{await request('/api/auth',{action:'logout'});setUnlocked(false);setProfiles([]);}}>Cerrar sesión</button></div>
 <section className="panel"><h2>Perfiles de la familia</h2><div className="profile-list">{profiles.map(p=><div key={p.id}><button className={profile===p.id?'primary':''} onClick={async()=>{setProfile(p.id);try{await load(p.id);}catch(e){setError((e as Error).message);}}}>{p.alias}</button><button className="small" onClick={()=>{setEditing(p.id);setAlias(p.alias);setAvatar(p.avatar);setBand(p.age_band);}}>Editar {p.alias}</button></div>)}</div><h3>{editing?'Editar perfil':'Crear un perfil'}</h3><form className="profile-form" onSubmit={e=>{e.preventDefault();void save();}}><label>Alias<input required maxLength={24} value={alias} onChange={e=>setAlias(e.target.value)}/></label><label>Avatar<select value={avatar} onChange={e=>setAvatar(e.target.value)}><option value="star">Estrella</option><option value="circle">Círculo</option><option value="triangle">Triángulo</option></select></label><label>Franja<select value={band} onChange={e=>setBand(e.target.value)}><option value="5-6">5-6 años</option><option value="7-8">7–8 años</option><option value="9-10">9-10 años</option></select></label><button className="primary" disabled={busy}>Guardar perfil</button></form></section>
 {profile&&<><h2>Así va {profiles.find(p=>p.id===profile)?.alias}</h2><div className="cards metrics"><article className="panel mint"><b>{totals.completed}</b><p>Sesiones terminadas</p></article><article className="panel peach"><b>{totals.firstCorrect} de {totals.firstTotal}</b><p>Primeras respuestas correctas sin pista</p></article><article className="panel lavender"><b>{totals.hints}</b><p>Intentos con ayuda</p></article></div><section className="panel"><h3>Actividad registrada</h3><p>{totals.interrupted} sesiones interrumpidas. Se muestran las últimas 100 sesiones.</p>{games.map(g=>{const s=summary(history.filter(r=>r.game===g.id));return <div className="chart-row" key={g.id}><b>{g.title}</b><meter min={0} max={Math.max(1,s.firstTotal)} value={s.firstCorrect} aria-label={`${g.title}: ${s.firstCorrect} de ${s.firstTotal}`}/><span>{s.firstCorrect} de {s.firstTotal}</span></div>})}<p className="notice">Estos indicadores describen respuestas del juego. No son una evaluación de capacidades ni permiten comparar niños.</p></section><section className="panel"><h2>Actividades y nivel</h2>{games.map(g=>{const s=settings.find(s=>s.activity_id===g.id);return <form className="settings-row" key={g.id+'-'+s?.enabled+'-'+s?.level} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void configure(g.id,f.get('enabled')==='on',Number(f.get('level')));}}><label><input name="enabled" type="checkbox" defaultChecked={s?.enabled!==false}/>{g.title}</label><label>Nivel<select name="level" defaultValue={s?.level??1}><option value={1}>1 · Inicio</option><option value={2}>2 · Práctica</option><option value={3}>3 · Reto</option></select></label><button disabled={busy}>Guardar {g.title}</button></form>})}<p>Los niveles se eligen según la práctica. La edad no determina automáticamente el nivel.</p></section></>}
 </>}
 <footer>Proyecto académico · Usar alias y datos de demostración hasta completar la revisión de participación.</footer></main>;
}
