'use client';
import Link from 'next/link';import {useEffect,useRef,useState} from 'react';
import {games,makeItems,evaluate,summary,type GameKind,type Attempt,type Result} from '@/lib/games';
import {request,toResults} from '@/lib/ui-data';
type Profile={id:string;alias:string;avatar:string};type Setting={activity_id:string;enabled:boolean;level:number};
export default function Studio({demo=false}:{demo?:boolean}){
 const [profiles,setProfiles]=useState<Profile[]>(demo?[{id:'example',alias:'Leo (ejemplo)',avatar:'star'}]:[]),[profile,setProfile]=useState(''),[settings,setSettings]=useState<Setting[]>([]),[history,setHistory]=useState<Result[]>([]);
 const [view,setView]=useState('profiles'),[game,setGame]=useState<GameKind>('catch'),[level,setLevel]=useState(1),[round,setRound]=useState(0),[attemptNo,setAttemptNo]=useState(1),[answer,setAnswer]=useState<number[]>([]),[hint,setHint]=useState(false),[showSequence,setShowSequence]=useState(true),[feedback,setFeedback]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[paused,setPaused]=useState(false),[result,setResult]=useState<Result|null>(null);
 const session=useRef(''),attempts=useRef<Attempt[]>([]),started=useRef(0),exposed=useRef(0),exposureMs=useRef(0),pauseTime=useRef(0),pending=useRef<Attempt|null>(null);
 const item=makeItems(game,level)[round];const totals=summary(history);
 useEffect(()=>{if(demo)return;request('/api/data').then(d=>setProfiles(d.profiles)).catch(e=>setError(e.message));},[demo]);
 async function choose(id:string){setError('');setProfile(id);if(!demo){try{const d=await request('/api/data?profile='+id);setSettings(d.settings);setHistory(toResults(d.sessions));}catch(e){setError((e as Error).message);return;}}setView('prepare');}
 function resetRound(){setAnswer([]);setHint(false);setShowSequence(true);setFeedback('');setAttemptNo(1);started.current=performance.now();exposed.current=performance.now();exposureMs.current=0;}
 async function start(kind:GameKind){setBusy(true);setError('');try{let selectedLevel=demo?level:(settings.find(s=>s.activity_id===kind)?.level??1);if(!demo){const d=await request('/api/data',{action:'start',profileId:profile,game:kind});session.current=d.data.id;selectedLevel=d.data.level;}else session.current=crypto.randomUUID();setGame(kind);setLevel(selectedLevel);setRound(0);attempts.current=[];resetRound();setView('play');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function sendAttempt(a:Attempt){setBusy(true);setError('');pending.current=a;try{if(!demo){const d=await request('/api/data',{action:'answer',sessionId:session.current,itemId:a.itemId,answer:a.answer,hintUsed:a.hintUsed,latencyMs:a.latencyMs,exposureMs:a.exposureMs,attemptNo:a.attemptNo});a.correct=d.data.correct;}attempts.current.push(a);pending.current=null;setFeedback(a.correct?'correct':a.attemptNo===2?'explain':'retry');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function submit(values:number[]){if(busy||feedback||paused||pending.current)return;setAnswer(values);void sendAttempt({itemId:item.id,answer:values,correct:evaluate(item,values),hintUsed:hint,latencyMs:Math.min(3600000,Math.max(0,Math.round(performance.now()-started.current))),exposureMs:exposureMs.current,attemptNo});}
 function select(n:number){if(game==='catch')submit([n]);else{const next=[...answer,n];setAnswer(next);const required=game==='race'?2:item.solution.length;if(next.length===required)submit(next);}}
 function retry(){setAnswer([]);setFeedback('');setAttemptNo(2);started.current=performance.now();}
 async function finish(status:'completed'|'interrupted'){setBusy(true);setError('');try{if(!demo)await request('/api/data',{action:status==='completed'?'complete':'interrupt',sessionId:session.current});const r:Result={id:session.current,game,level,status,attempts:[...attempts.current],createdAt:new Date().toISOString()};setResult(r);setHistory(h=>h.some(x=>x.id===r.id)?h:[r,...h]);setView(status==='completed'?'result':'catalog');setPaused(false);}catch(e){setError('Tu resultado todavía no está guardado. '+(e as Error).message);}finally{setBusy(false);}}
 function next(){if(round===4){void finish('completed');return;}setRound(r=>r+1);resetRound();}
 function listen(){if(!('speechSynthesis'in window)){setError('El audio no está disponible en este navegador. Puedes seguir con el texto.');return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(view==='play'?item.prompt:'Elige tu aventura. Puedes pedir ayuda o descansar cuando quieras.');u.lang='es-ES';speechSynthesis.speak(u);}
 const name=profiles.find(p=>p.id===profile)?.alias;
 return <main id="main" className="app-shell"><header className="app-header"><Link href="/" className="brand">edukids</Link><span className="tag">{demo?'Demo · sin guardado':name??'Dispositivo familiar'}</span><button onClick={listen}>Escuchar</button>{view==='play'?<button disabled={busy} onClick={()=>{setPaused(true);pauseTime.current=performance.now();}}>Pausa</button>:<Link className="button small" href="/familia">Familias</Link>}</header>
 {error&&<div className="error" role="alert">{error}{pending.current&&<button disabled={busy} onClick={()=>void sendAttempt(pending.current!)}>Reintentar envío</button>}</div>}
 {view==='profiles'&&<><p className="eyebrow">TU AVENTURA COMIENZA AQUÍ</p><h1>¿Quién va a jugar?</h1><p className="lead">Toca tu dibujo para entrar.</p><div className="cards">{profiles.map(p=><button className="profile-card" key={p.id} onClick={()=>void choose(p.id)}><span>{p.avatar==='star'?'★':p.avatar==='triangle'?'▲':'●'}</span><b>{p.alias}</b></button>)}</div>{!profiles.length&&<p>Aún no hay perfiles disponibles. <Link href="/familia">Una persona adulta puede entrar y crear uno.</Link></p>}</>}
 {view==='prepare'&&<><h1>Antes de jugar</h1><section className="panel"><p className="lead">Busca un sitio cómodo y apoya la tableta para verla bien.</p><p>Puedes descansar cuando quieras.</p></section><button className="primary" onClick={()=>setView('catalog')}>Estoy listo</button></>}
 {view==='catalog'&&<><p className="eyebrow">A TU RITMO</p><h1>Elige tu aventura</h1>{demo&&<label>Nivel de la demo <select value={level} onChange={e=>setLevel(Number(e.target.value))}><option value={1}>1 · Inicio</option><option value={2}>2 · Práctica</option><option value={3}>3 · Reto</option></select></label>}<div className="cards">{games.filter(g=>demo||settings.find(s=>s.activity_id===g.id)?.enabled!==false).map(g=><button key={g.id} disabled={busy} className={'game-card '+g.tone} onClick={()=>void start(g.id)}><span className="symbol">{g.symbol}</span><h2>{g.title}</h2><p>{g.description}</p><span>5 retos · Sin límite de tiempo</span></button>)}</div>{!demo&&games.every(g=>settings.find(s=>s.activity_id===g.id)?.enabled===false)&&<p>No hay juegos habilitados. Una persona adulta puede cambiarlo en Familias.</p>}<div className="actions"><button onClick={()=>setView('progress')}>Mi camino</button><button onClick={()=>setView('profiles')}>Cambiar de perfil</button></div></>}
 {view==='play'&&<><p className="eyebrow">{games.find(g=>g.id===game)?.title} · Nivel {level} · Reto {round+1} de 5</p><h1>{game==='memory'&&!showSequence?'Toca los números en el mismo orden':item.prompt}</h1><section className="exercise" aria-busy={busy}>
 {game==='memory'&&showSequence?<><div className="sequence">{item.sequence?.map((n,i)=><span key={i}>{n}</span>)}</div><p>Cuando estés preparado, los escondemos.</p><button className="primary" onClick={()=>{exposureMs.current=Math.min(3600000,Math.round(performance.now()-exposed.current));setShowSequence(false);started.current=performance.now();}}>Ya los recuerdo</button></>:<>
 {game==='race'&&<p className="math">{item.start} {answer.map((n,i)=><span key={i}> + {n}</span>)} → {item.target}</p>}
 {game==='memory'&&<p className="math" aria-live="polite">{Array.from({length:item.solution.length},(_,i)=>answer[i]??'□').join(' · ')}</p>}
 <div className="answers">{item.options.map(n=><button key={n} disabled={busy||!!feedback||paused||!!pending.current} className={answer.includes(n)?'selected':''} onClick={()=>select(n)}>{game==='race'?'+ ':''}{n}</button>)}</div>
 </>}
 {hint&&<p className="hint">{item.hint}</p>}
 <div className="feedback" role="status">{feedback==='correct'&&'✓ ¡Lo has encontrado!'}{feedback==='retry'&&'Vamos a probar otra vez. Puedes pedir una pista.'}{feedback==='explain'&&`La respuesta es ${item.solution.join(game==='race'?' + ':' · ')}. Seguimos aprendiendo.`}</div>
 {feedback==='retry'&&<button className="primary" onClick={retry}>Volver a intentarlo</button>}{['correct','explain'].includes(feedback)&&<button className="primary" disabled={busy} onClick={next}>{round===4?'Terminar y guardar':'Siguiente reto'}</button>}
 </section><div className="actions"><button disabled={busy||!!feedback} onClick={()=>{setHint(true);if(game==='memory'){setShowSequence(true);setAnswer([]);exposed.current=performance.now();}}}>{game==='memory'?'Volver a mirar':'Dame una pista'}</button>{game!=='catch'&&<button disabled={busy||!!feedback} onClick={()=>setAnswer(a=>a.slice(0,-1))}>Deshacer último toque</button>}</div></>}
 {paused&&<div className="modal" role="dialog" aria-modal="true" aria-labelledby="pause-title"><section className="panel"><h2 id="pause-title">Puedes descansar</h2><p>Al salir, el intento quedará interrumpido. Si recargas la página no se recupera el ejercicio abierto.</p><div className="actions"><button className="primary" onClick={()=>{started.current+=performance.now()-pauseTime.current;setPaused(false);}}>Seguir jugando</button><button disabled={busy} onClick={()=>void finish('interrupted')}>Terminar por hoy</button></div></section></div>}
 {view==='result'&&<><h1>Has terminado tu actividad</h1><section className="panel mint"><p className="lead">{demo?'Has completado cinco retos en la demo.':'✓ Tu resultado se ha guardado.'}</p><p>{result?.attempts.filter(a=>a.attemptNo===1&&a.correct&&!a.hintUsed).length} de 5 retos resueltos a la primera sin pista.</p><p>Puedes seguir aprendiendo o descansar.</p></section><div className="actions"><button className="primary" onClick={()=>setView('progress')}>Ver mi camino</button><button onClick={()=>setView('catalog')}>Otro juego</button></div></>}
 {view==='progress'&&<><h1>Mi camino</h1><section className="panel"><p className="lead">{totals.completed} {totals.completed===1?'actividad terminada':'actividades terminadas'}</p>{history.length?<ul>{history.map(r=><li key={r.id}>{games.find(g=>g.id===r.game)?.title} · Nivel {r.level} · {r.status==='completed'?'Terminada':'Interrumpida'}</li>)}</ul>:<p>Aún no has terminado una actividad. Tu camino empieza cuando quieras.</p>}</section><button className="primary" onClick={()=>setView('catalog')}>Elegir otro juego</button></>}
 <footer>{demo?'Los datos de esta demo desaparecen al recargar.':'Los resultados se guardan en la base de datos configurada.'} · Sin anuncios, monedas ni comparaciones.</footer></main>;
}
